/*
 * FLASHCARDS — Flashcard mode
 * Each card: { id, chapter, front, back }
 * front: question/prompt (plain text)
 * back: answer (HTML string, may use <strong>, <br>)
 */
var FLASHCARDS = [
  { id: 'FC-01', chapter: 'L1', front: 'What are Skemp\'s two types of understanding?', back: '<strong>Relational</strong> = knowing what to do AND why.<br><strong>Instrumental</strong> = rules without reasons.<br><br>Instrumental learners can\'t adapt when they forget rules; relational learners can reconstruct from understanding.' },
  { id: 'FC-02', chapter: 'L1', front: 'In Piaget\'s constructivism, what is the difference between assimilation and accommodation?', back: '<strong>Assimilation</strong> = fitting new info into existing schema (schema unchanged).<br><strong>Accommodation</strong> = changing existing schema to fit new info.<br><br>Both are ways learners construct knowledge.' },
  { id: 'FC-03', chapter: 'L1', front: 'What is Skemp\'s Principle of Learning Maths (1987)?', back: 'Higher-order concepts cannot be taught by definition \u2014 only by <strong>suitable examples</strong>. Always: examples first \u2192 definition after.' },
  { id: 'FC-04', chapter: 'L1', front: 'What is metacognition?', back: 'Thinking about thinking: <strong>awareness, monitoring, self-regulation</strong>. Build reflection into the end of every lesson.' },
  { id: 'FC-05', chapter: 'L1', front: 'What are the 5 components of the Pentagon Model?', back: 'Centre: <strong>Mathematical Problem Solving</strong>.<br><br>Five components: <strong>Concepts \u00b7 Skills \u00b7 Processes \u00b7 Metacognition \u00b7 Dispositions</strong> (Dispositions replaces Attitudes from 2028).' },
  { id: 'FC-06', chapter: 'L2', front: 'Name the four curriculum types.', back: '<strong>Intended</strong> (national syllabus/MOE) \u2192 <strong>Planned</strong> (school scheme of work) \u2192 <strong>Enacted</strong> (what teacher actually teaches) \u2192 <strong>Experienced</strong> (what students actually learn).<br><br>Gaps between levels are where learning breaks down.' },
  { id: 'FC-07', chapter: 'L2', front: 'What are the 4 steps in P\u00f3lya\'s problem-solving strategy?', back: '1. <strong>Understand</strong> the problem.<br>2. <strong>Devise a plan</strong>.<br>3. <strong>Carry out</strong> the plan.<br>4. <strong>Check and expand</strong>.<br><br>The process is non-linear \u2014 looping back is expected.' },
  { id: 'FC-08', chapter: 'L2', front: 'What distinguishes a mathematical problem from an exercise?', back: 'A <strong>problem</strong> has no immediately available procedure and requires motivation/engagement. An <strong>exercise</strong> uses a known procedure. The solver must accept and attempt the problem.' },
  { id: 'FC-09', chapter: 'L2', front: 'What does PORA stand for in the Nature of Mathematics?', back: '<strong>P</strong>roperties &amp; Relationships (Concepts) \u00b7 <strong>O</strong>perations &amp; Algorithms (Skills) \u00b7 <strong>R</strong>epresentations &amp; Communications (Processes) \u00b7 <strong>A</strong>bstractions &amp; Applications (Processes).' },
  { id: 'FC-10', chapter: 'L2', front: 'Name the 8 Big Ideas in secondary mathematics.', back: '<strong>F</strong>unctions \u00b7 <strong>I</strong>nvariance \u00b7 <strong>N</strong>otations \u00b7 <strong>D</strong>iagrams \u00b7 <strong>P</strong>roportionality \u00b7 <strong>M</strong>easures \u00b7 <strong>M</strong>odels \u00b7 <strong>E</strong>quivalence.<br><br>Primary excludes Functions &amp; Models.' },
  { id: 'FC-11', chapter: 'L2', front: 'What are the 4 modes of learning mathematics?', back: 'Through <strong>practice</strong> (exercises) \u00b7 <strong>Through</strong> problem solving (hard problems) \u00b7 <strong>For</strong> problem solving (applications) \u00b7 <strong>About</strong> problem solving (explicit heuristic teaching).' },
  { id: 'FC-12', chapter: 'L3', front: 'Why use ICT in maths education? (Turkle & Papert)', back: '"The computer has the ability to make the abstract concrete." ICT bridges the gap between abstract concepts and concrete experiences. Use it <strong>only when it genuinely enhances student learning</strong>.' },
  { id: 'FC-13', chapter: 'L3', front: 'Why should you NOT use PowerPoint for worked examples?', back: 'Fixed pace \u2014 students can\'t follow. Can\'t pause to question at each step. Undermines constructivism. Use <strong>whiteboard</strong> instead for step-by-step working with questioning. PPT is fine for pictures only.' },
  { id: 'FC-14', chapter: 'L3', front: 'What does LOVE stand for?', back: '<strong>L</strong>inking <strong>O</strong>pportunities in a <strong>V</strong>ariety of <strong>E</strong>xperiences to the learning of maths. Use varied resources but always <strong>link the activity back to mathematics</strong>.' },
  { id: 'FC-15', chapter: 'L4', front: 'What is Bruner\'s C-P-A approach?', back: '<strong>Concrete \u2192 Pictorial \u2192 Abstract</strong>. Hyphens = linked stages, not separate methods. Use manipulatives \u2192 diagrams \u2192 symbols. For lower-readiness students, never start with abstraction.' },
  { id: 'FC-16', chapter: 'L4', front: 'What is the extended C-P-A approach?', back: 'When no physical manipulative exists, use <strong>concrete examples (numbers)</strong> as the concrete stage. What\'s abstract at one level becomes concrete at a higher level (Primary: objects, Secondary: numbers, University: algebra).' },
  { id: 'FC-17', chapter: 'L4', front: 'Describe the "We do one. You do more." teaching structure.', back: 'WE1 (done together, on board) \u2192 Practice Q1 (similar, WE1 visible) \u2192 Q2+ (slight difficulty increase) \u2192 WE2 (when students can\'t handle next level). No copying WEs \u2014 Practice Q1 replaces it. Deliberate progression throughout.' },
  { id: 'FC-18', chapter: 'L5', front: 'What are the 6 stages of Shulman\'s Pedagogical Reasoning?', back: 'Comprehension \u2192 <strong>Transformation</strong> \u2192 Instruction \u2192 Evaluation \u2192 Reflection \u2192 New Comprehension.<br><br>Transformation is the core teaching act. <em>Docendo discimus</em> \u2014 "by teaching, we learn."' },
  { id: 'FC-19', chapter: 'L5', front: 'What are the 4 sub-aspects of Transformation (Shulman)?', back: '<strong>Preparation</strong> (interpret materials, detect errors) \u2192 <strong>Representation</strong> (analogies, examples, demos) \u2192 <strong>Selection</strong> (choose instructional approach) \u2192 <strong>Adaptation</strong> (tailor to students).<br><br>Unpack content first, then choose method.' },
  { id: 'FC-20', chapter: 'L5', front: 'Name Backhouse\'s 5 elements of mathematical content and how to teach each.', back: '<strong>Concept</strong> (explain/develop) \u00b7 <strong>Convention</strong> (just tell, no "why") \u00b7 <strong>Result</strong> (prove/derive) \u00b7 <strong>Technique</strong> (demo with worked examples) \u00b7 <strong>Process</strong> (provide thinking opportunities).<br><br>Convention is most mishandled; Process is most neglected.' },
  { id: 'FC-21', chapter: 'L6', front: 'What is the difference between ratio and rate?', back: '<strong>Ratio</strong> compares \u22652 quantities of the <strong>same kind</strong> (no units). <strong>Rate</strong> measures how one quantity varies with another (same or different kinds, always exactly 2 quantities). Rate comparing different kinds cannot become ratio.' },
  { id: 'FC-22', chapter: 'L6', front: 'Give the 5 equivalent statements for direct proportion (y \u221d x).', back: '1. x\u00d7n \u2192 y\u00d7n (multiplicative).<br>2. y\u2082/y\u2081 = x\u2082/x\u2081 (equal ratios).<br>3. y\u2082/x\u2082 = y\u2081/x\u2081 (equal rates).<br>4. y/x = k (constant).<br>5. y = kx (line through origin).<br><br>Additive reasoning (constant difference) is NOT sufficient.' },
  { id: 'FC-23', chapter: 'L6', front: 'How does inverse proportion differ from direct proportion in terms of what stays constant?', back: 'Direct proportion: <strong>rate y/x is constant</strong> (y = kx).<br>Inverse proportion: <strong>product xy is constant</strong> (y = k/x).<br><br>In inverse proportion, when x\u00d7n \u2192 y\u00f7n.' },
  { id: 'FC-24', chapter: 'T1', front: 'What is the preferred definition of a prime number?', back: 'A whole number with <strong>exactly two different factors</strong>. Not "divisible by 1 and itself" (which includes 1). The word "exactly" is critical.' },
  { id: 'FC-25', chapter: 'T1', front: 'Is 1 prime, composite, or neither?', back: '<strong>Neither.</strong> 1 has exactly one factor (itself), so it doesn\'t meet the prime definition (exactly two factors) or composite definition (more than two factors).' },
  { id: 'FC-26', chapter: 'T1', front: 'Why is HCF(6, 12) a bad first example for teaching HCF?', back: 'Because HCF(6, 12) = 6, which equals the smaller number. Students may generalise that HCF is always the smaller number. Better first example: <strong>HCF(4, 7) = 1</strong> \u2014 challenges the assumption.' },
  { id: 'FC-27', chapter: 'T1', front: 'What is the correct questioning sequence when testing for understanding?', back: 'Ask the question \u2192 <strong>pause ~3 seconds</strong> \u2192 then nominate a specific student. If you nominate first, other students stop thinking. Use choral response only when NOT testing understanding.' },
  { id: 'FC-28', chapter: 'T1', front: 'Name the 5 concepts for teaching negative number operations with algebra discs.', back: '1. Add two negatives.<br>2. Add positive + negative (zero pairs cancel).<br>3. Subtract larger positive from smaller positive (add zero pairs).<br>4. Subtract positive from negative.<br>5. Subtract a negative (removing negatives = adding positives).' },
  { id: 'FC-29', chapter: 'T2a', front: 'What are the three uses of a letter in algebra?', back: '1. <strong>Specific unknown</strong> \u2014 one fixed value (e.g. price = x).<br>2. <strong>Variable</strong> \u2014 ranges over values (e.g. y = 2x+1).<br>3. <strong>Parameter</strong> \u2014 fixed for a given case, varies across cases (e.g. m, c in y = mx + c).' },
  { id: 'FC-30', chapter: 'T2a', front: 'What is the equal sign misconception in algebra?', back: 'Students treat = as "do something to get an answer" instead of <strong>equivalence between two sides</strong>. This is a conceptual misconception. Fix: use a balance (physical or virtual) to show equality as balance.' },
  { id: 'FC-31', chapter: 'T2a', front: 'Name the 4 algebraic action words and what each means.', back: '<strong>Expand</strong> (remove brackets) \u00b7 <strong>Simplify</strong> (combine like terms) \u00b7 <strong>Factorise</strong> (reverse of expansion, extract common factors) \u00b7 <strong>Solve</strong> (find values satisfying the equation). Students must distinguish all four.' },
  { id: 'FC-32', chapter: 'T3', front: 'Why should you NOT teach the y-intercept meaning of b in y = ax + b at Sec 1?', back: 'The Sec 1 syllabus uses y = ax + b, but students learn that b = y-intercept only in <strong>Sec 3</strong> (G6.3). Teaching it early violates the <strong>spiral curriculum</strong> \u2014 teach concepts appropriate to the level.' },
  { id: 'FC-33', chapter: 'T3', front: 'A student draws a vertical line for "height of flag vs time during flag-raising." What misconception does this reveal?', back: 'The student treats a graph as a <strong>visual/pictorial representation</strong> of the physical situation (a flagpole). Correct understanding: a graph is an <strong>abstract representation of the relationship between two variables</strong>, not a picture.' },
  { id: 'FC-34', chapter: 'T3', front: 'Why should you NOT teach "x-intercepts are h and k" for y = (x\u2212h)(x\u2212k)?', back: 'Students make sign errors: e.g. for y = (x+1)(x+5), they say x-intercepts are 1 and 5 (wrong \u2014 they are \u22121 and \u22125). <strong>Better approach:</strong> Always just solve the equation = 0 to find x-intercepts.' },
  { id: 'FC-35', chapter: 'T3', front: 'What is the difference between gradient (y/x) and rate of change (dy/dx)?', back: 'Rate y/x \u2260 rate of change dy/dx in general. They are equal <strong>only when the line passes through the origin</strong> (y = kx). For y = kx + c where c \u2260 0, the rate y/x varies but dy/dx is constant.' }
];
